/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the rails SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx petUpdatePet.ts
 */

import { Rails } from "rails";

const rails = new Rails({
  apiKey: process.env["RAILS_API_KEY"] ?? "",
});

async function main() {
  const result = await rails.updatePet({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value 1>",
    ],
  });

  console.log(result);
}

main().catch(console.error);
