workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Rails PoC API:
        inputs:
            - location: https://raw.githubusercontent.com/sibabale/rails/main/poc/api/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/rails/poc/rails-po-c-api
targets:
    rails:
        target: typescript
        source: Rails PoC API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/rails/poc/rails-po-c-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
